name: makemkv
summary: Backup your Bluray and DVD discs
description: |
  Backup your Bluray and DVD discs

grade: devel
confinement: devmode
adopt-info: get-version

architectures:
- build-on: amd64
- build-on: i386

plugs:
  optical-drive:
    write: true

apps:
  makemkv:
    command: desktop-launch $SNAP/usr/bin/makemkv
    desktop: usr/share/applications/makemkv.desktop
    environment:
      MAKEMKVCON: $SNAP/usr/bin/makemkvcon
      JAVA_HOME: $SNAP/usr
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - home
    - opengl
    - optical-drive
    - process-control
    - removable-media
    - wayland
    - x11

  makemkvcon:
    command: usr/bin/makemkvcon
    environment:
      JAVA_HOME: $SNAP/usr
    plugs:
    - hardware-observe
    - home
    - optical-drive
    - process-control
    - removable-media

parts:
  libav:
    source: https://ffmpeg.org/releases/ffmpeg-4.1.tar.xz
    plugin: autotools
    build-packages:
    - libfdk-aac-dev
    - yasm
    configflags:
    - --prefix=/usr
    - --enable-static
    - --disable-shared
    - --enable-pic
    - --enable-libfdk-aac
    stage-packages:
    - libfdk-aac0
    - libxcb-shape0

  patches:
    plugin: dump
    source: ./patches
    prime:
    - -*

  get-version:
    plugin: dump
    build-packages:
    - curl
    override-pull: |
      VERSION="$(curl --silent --show-error --location \
        'https://makemkv.com/forum/viewtopic.php?f=3&t=224' \
        | grep -E 'http://www.makemkv.com/download/makemkv-bin-[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz' \
        | head -n1 | sed -E -e \
          's|^.*\"http://www.makemkv.com/download/makemkv-bin-([0-9]+\.[0-9]+\.[0-9]+)\.tar\.gz\".*|\1|')"
      echo "Setting snap version to '$VERSION'"
      snapcraftctl set-version "$VERSION"
      echo "$VERSION" > version
    prime: [-*]

  makemkv-oss:
    after: [get-version, desktop-qt5, patches, libav]
    plugin: autotools
    build-packages:
    - curl
    - libexpat1-dev
    - libegl1-mesa-dev
    - libgl1-mesa-dev
    - libssl-dev
    - qtbase5-dev
    - tar
    override-pull: |
      curl --silent --show-error --location "http://www.makemkv.com/download/makemkv-oss-$(cat "$SNAPCRAFT_STAGE/version").tar.gz" | tar xz --strip-components=1
    override-build: |
      patch -Np1 < $SNAPCRAFT_STAGE/patch.diff
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/128x128/apps/makemkv.png|' makemkvgui/share/makemkv.desktop
      snapcraftctl build
    configflags:
    # - --prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr
    - --prefix=/usr
    stage-packages:
    - libexpat1
    - libgconf-2-4
    - libqt5core5a
    - libqt5dbus5
    - libqt5gui5
    - libqt5widgets5
    - libqt5waylandclient5
    - libssl1.0.0
    - libwayland-client0
    - libwayland-cursor0
    - libx11-6
    - qtwayland5

  makemkv-bin:
    after: [get-version]
    plugin: make
    build-packages:
    - default-jre # used to work out the right symlink dir in `override-build`
    - execstack
    override-pull: |
      curl --silent --show-error --location "http://www.makemkv.com/download/makemkv-bin-$(cat "$SNAPCRAFT_STAGE/version").tar.gz" | tar xz --strip-components=1
    override-build: |
      mkdir tmp && touch tmp/eula_accepted
      execstack -c bin/amd64/makemkvcon
      execstack -c bin/i386/makemkvcon

      snapcraftctl build

      JDK=$(find /usr/lib/jvm -type d -name "java-8-openjdk-*" | head -n1 | xargs basename)
      JDKBIN=../lib/jvm/$JDK/jre/bin
      for exec in java javaws jexec jjs; do
        ln -sf $JDKBIN/$exec $SNAPCRAFT_PART_INSTALL/usr/bin/$exec
      done
    stage:
    - -usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
    stage-packages:
    - default-jre
