name: makemkv
version: '1.10.9'
summary: Backup your Bluray discs
description: |
  Backup your Bluray discs - Console only, currently.
  Run makemkv.makemkvcon in a terminal to use.

grade: devel
confinement: strict

apps:
  # makemkv:
  #   command: desktop-launch $SNAP/bin/snapcraft-preload $SNAP/usr/bin/makemkv
  #   plugs:
  #     - account-control
  #     - desktop
  #     - home
  #     - opengl
  #     - optical-drive
  #     - process-control
  #     - removable-media
  #     - wayland
  #     - x11
  #   environment:
  #     MAKEMKVCON: $SNAP/command-makemkvcon.wrapper
  
  makemkvcon:
    command: snapcraft-preload $SNAP/usr/bin/makemkvcon
    plugs:
      - home
      - optical-drive
      - process-control
      - removable-media

parts:
  libav:
    plugin: autotools
    source: http://ffmpeg.org/releases/ffmpeg-3.4.tar.bz2
    configflags:
      - --prefix=/usr
      - --enable-pic
      - --disable-shared
      - --enable-libfdk-aac
      - --disable-cuda
      - --disable-cuvid
    build-packages:
      - libfdk-aac-dev
      - yasm
    prime:
      - -*
  
  makemkv-oss:
    after: [desktop-qt4, libav, snapcraft-preload]
    plugin: autotools
    source: http://www.makemkv.com/download/makemkv-oss-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    configflags:
      - --prefix=/usr
    build-packages:
      - libexpat1-dev
      - libgl1-mesa-dev
      - libqt4-dev
      - libssl-dev
    stage-packages:
      - libexpat1
      - libssl1.0.0
  
  makemkv-bin:
    plugin: make
    source: http://www.makemkv.com/download/makemkv-bin-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    prepare: |
      mkdir tmp && touch tmp/eula_accepted
      execstack -c bin/amd64/makemkvcon
      execstack -c bin/i386/makemkvcon
      execstack -c bin/i386/mmdtsdec
    build-packages:
      - execstack
    stage-packages:
      - default-jre