name: makemkv
version: '1.14.1'
summary: Backup your Bluray and DVD discs
description: |
  Backup your Bluray and DVD discs

grade: devel
confinement: devmode

architectures:
- build-on: amd64
- build-on: i386

plugs:
  optical-drive:
    write: true

apps:
  makemkv:
    command: desktop-launch $SNAP/usr/bin/makemkv
    desktop: usr/share/applications/makemkv.desktop
    environment:
      MAKEMKVCON: $SNAP/usr/bin/makemkvcon
      JAVA_HOME: $SNAP/usr
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - home
    - opengl
    - optical-drive
    - process-control
    - removable-media
    - wayland
    - x11

  makemkvcon:
    command: usr/bin/makemkvcon
    environment:
      JAVA_HOME: $SNAP/usr
    plugs:
    - hardware-observe
    - home
    - optical-drive
    - process-control
    - removable-media

parts:
  libav:
    source: https://ffmpeg.org/releases/ffmpeg-4.1.tar.xz
    plugin: autotools
    build-packages:
    - libfdk-aac-dev
    - yasm
    configflags:
    - --prefix=/usr
    - --enable-static
    - --disable-shared
    - --enable-pic
    - --enable-libfdk-aac
    stage-packages:
    - libfdk-aac0
    - libxcb-shape0

  patches:
    plugin: dump
    source: ./patches
    prime:
    - -*

  makemkv-oss:
    after: [desktop-qt5, patches, libav]
    source: http://www.makemkv.com/download/makemkv-oss-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: autotools
    build-packages:
    - libexpat1-dev
    - libegl1-mesa-dev
    - libgl1-mesa-dev
    - libssl-dev
    - qtbase5-dev
    override-build: |
      patch -Np1 < $SNAPCRAFT_STAGE/patch.diff
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/128x128/apps/makemkv.png|' makemkvgui/share/makemkv.desktop
      snapcraftctl build
    configflags:
    # - --prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr
    - --prefix=/usr
    stage-packages:
    - libexpat1
    - libgconf-2-4
    - libqt5core5a
    - libqt5dbus5
    - libqt5gui5
    - libqt5widgets5
    - libqt5waylandclient5
    - libssl1.0.0
    - libwayland-client0
    - libwayland-cursor0
    - libx11-6
    - qtwayland5

  makemkv-bin:
    after: [snapcraft-preload]
    source: http://www.makemkv.com/download/makemkv-bin-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: make
    build-packages:
    - default-jre # used to work out the right symlink dir in `override-build`
    - execstack
    override-build: |
      mkdir tmp && touch tmp/eula_accepted
      execstack -c bin/amd64/makemkvcon
      execstack -c bin/i386/makemkvcon

      snapcraftctl build

      mv $SNAPCRAFT_PART_INSTALL/usr/bin/makemkvcon $SNAPCRAFT_PART_INSTALL/usr/bin/makemkvcon.real

      JDK=$(find /usr/lib/jvm -type d -name "java-8-openjdk-*" | head -n1 | xargs basename)
      JDKBIN=../lib/jvm/$JDK/jre/bin
      for exec in java javaws jexec jjs; do
        ln -sf $JDKBIN/$exec $SNAPCRAFT_PART_INSTALL/usr/bin/$exec
      done

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/usr/bin/makemkvcon
      #!/bin/sh
      exec \$SNAP/bin/snapcraft-preload \$SNAP/usr/bin/makemkvcon.real "\$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/makemkvcon
    stage:
    - -usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
    stage-packages:
    - default-jre
