name: Check for new releases

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: get-latest-version
      run: |
        VERSION="$(curl --silent --show-error --location 'https://makemkv.com/forum/viewtopic.php?f=3&t=224' \
          | grep -E 'http://www.makemkv.com/download/makemkv-bin-[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz' \
          | head -n1 \
          | sed -E -e 's|^.*\"http://www.makemkv.com/download/makemkv-bin-([0-9]+\.[0-9]+\.[0-9]+)\.tar\.gz\".*|\1|')"
        EDGEVER="$(snap info makemkv | awk '$1 == "latest/edge:" { print $2 }')"
        if [ "$VERSION" != "$EDGEVER" ]; then
          echo "$(date -u --rfc-3339=seconds) Version $VERSION" >> .build.stamp
        fi
    - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Trigger build for new version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
